**Consider the below code to answer further questions:**

In [2]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there is difference between the data type of both the variable i.e **list_** & **array_list**.  
list_ containing the string integer while array_list containg **1D** array of a list items.  

**code:** Writing a code for printing the Datatype's of both the variable

In [5]:
print(f"Type of a list_:{type(list_)}\nType of a array_list:{type(array_list)}")

Type of a list_:<class 'list'>
Type of a array_list:<class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [16]:
print("For list_ variable")
for i in list_:
    print(f"type of {i} element in list_ is {type(i)}")

print("For array_list variable")    
for j in array_list:
    print(f"type of {j} element in array_list is {type(j)}")

For list_ variable
type of 1 element in list_ is <class 'str'>
type of 2 element in list_ is <class 'str'>
type of 3 element in list_ is <class 'str'>
type of 4 element in list_ is <class 'str'>
type of 5 element in list_ is <class 'str'>
For array_list variable
type of 1 element in array_list is <class 'numpy.str_'>
type of 2 element in array_list is <class 'numpy.str_'>
type of 3 element in array_list is <class 'numpy.str_'>
type of 4 element in array_list is <class 'numpy.str_'>
type of 5 element in array_list is <class 'numpy.str_'>


### Q3. Considering the following changes in the variable,

In [36]:
array_list: array_list = np.array(object = list_, dtype = int)   

**Will there be any difference in the data type of the elements present in both the variables, list_ and**
**arra_list? If so then print the data types of each and every element present in both the variables, list_**
**and arra_list.**

Yes, there is the difference between the datatype of both the variable **list_ & array_list**, because while creating the array_list, there is discribed the datatype **int** by passing the parameter.

printing the Datatype of each and every element in the both variable.

In [38]:
print("For list_ variable")
for i in list_:
    print(f"type of {i} element in list_ is {type(i)}")

print("For array_list variable")    
for j in array_list:
    print(f"type of {j} element in array_list is {type(j)}")

For list_ variable
type of 1 element in list_ is <class 'str'>
type of 2 element in list_ is <class 'str'>
type of 3 element in list_ is <class 'str'>
type of 4 element in list_ is <class 'str'>
type of 5 element in list_ is <class 'str'>
For array_list variable
type of 1 element in array_list is <class 'numpy.int32'>
type of 2 element in array_list is <class 'numpy.int32'>
type of 3 element in array_list is <class 'numpy.int32'>
type of 4 element in array_list is <class 'numpy.int32'>
type of 5 element in array_list is <class 'numpy.int32'>


**Consider the below code to answer further questions:**

In [33]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

### Q4. Write a code to find the following characteristics of variable, num_array:
**(i) shape**  
**(ii) size**

We can find the **shape** of a **num_array** variable by using the numpy fucntion **.shape**.  
This function is used to find the shape of a any array matrix.  

In [34]:
num_array.shape

(2, 3)

we can find the **size** of a variable **num_array** by using the numpy function **.size**.  
This function is used to find the size of a any array matrix.  

In [35]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

creating a numpy array of a **3x3** matrix containing zero only, using a numpy fuction **numpy.zeros()**.  
this fuction is used to create a array matrix of any shape which containg **0** only.  

In [30]:
zeros_matrix = np.zeros((3, 3))
print(zeros_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Q6. Create an identity matrix of shape (5,5) using numpy functions?

Creating a **identity matrix** of shape (5,5) using numpy function **numpy.eye**.  
**numpy.eye** funcion in numpy used to create a identity matrix, we can create a identity matrix of any shape , just passing the shape as a parameter.

In [17]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])